"""
base_rule.py — Abstract base class and shared data structures for NetGuard detection rules.

Every detection rule must inherit from BaseRule and implement all abstract methods.
This enforces the plug-and-play interface that allows new attack types to be added
without modifying the Detection_Engine.

The FlowData dataclass provides a common per-source-IP accumulator used by
volumetric rules (SYN flood, port scan, brute force).

Requirements: 9.3, 9.4, 9.7
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Optional

from detection.parsers.packet_decoder import Packet


# ---------------------------------------------------------------------------
# Shared data structures
# ---------------------------------------------------------------------------

@dataclass
class FlowData:
    """
    Per-source-IP accumulator for a single detection rule.

    Maintained by the Flow_Tracker dict inside each rule:
        flow_tracker: dict[str, FlowData]  keyed by source_ip

    Fields are selectively used by different rule types:
    - timestamps: used by SYN flood, port scan, brute force
    - ports: used by port scan (set of destination ports)
    - macs: used by ARP spoof (maps IP -> set of MAC addresses)
    - extra: generic overflow bucket for rule-specific data
    """

    timestamps: deque = field(default_factory=lambda: deque())
    """Deque of ISO-8601 timestamp strings within the current sliding window."""

    ports: set = field(default_factory=set)
    """Set of (dst_ip, dst_port) tuples for port scan tracking."""

    macs: dict = field(default_factory=dict)
    """dict[ip_str, set[mac_str]] for ARP spoof tracking."""

    extra: dict = field(default_factory=dict)
    """Rule-specific overflow data."""


# ---------------------------------------------------------------------------
# ThreatEvent dataclass (generated by rules)
# ---------------------------------------------------------------------------

@dataclass
class ThreatEvent:
    """
    Structured threat event emitted by a detection rule on confirmed detection.

    Passed to the ExplainabilityEngine then the PreventionEngine.
    Persisted to the events table in the database.
    """

    event_id: str
    """UUID4 string — unique across the application lifetime."""

    timestamp: str
    """UTC ISO-8601 string at detection time."""

    attack_type: str
    """Human-readable attack category: SYN Flood | Port Scan | SQL Injection | Brute Force | ARP Spoofing."""

    source_ip: str
    """Source IP of the attacker."""

    destination_ip: Optional[str]
    """Primary destination IP, or None when not applicable."""

    source_port: Optional[int]
    """Source port, or None."""

    destination_port: Optional[int]
    """Destination port, or None."""

    protocol: str
    """Protocol: TCP | UDP | ICMP | ARP | UNKNOWN."""

    rule_name: str
    """Detection rule identifier: SYN_FLOOD_001, PORT_SCAN_001, etc."""

    severity: str
    """Severity level: Low | Medium | High | Critical."""

    confidence: int
    """Confidence score in range [0, 100]."""

    packet_count: int
    """Number of packets contributing to this detection."""

    evidence: dict
    """Structured evidence dict (serialised to JSON in the database)."""

    blocked: bool = False
    """Set to True by the PreventionEngine after a successful iptables block."""


# ---------------------------------------------------------------------------
# Explanation dataclass (generated by ExplainabilityEngine)
# ---------------------------------------------------------------------------

@dataclass
class Explanation:
    """
    Human-readable explanation attached to every ThreatEvent.

    Generated by ExplainabilityEngine and persisted alongside the event.
    """

    attack_name: str
    """Human-readable attack name (same as ThreatEvent.attack_type)."""

    rule_triggered: str
    """Rule identifier that triggered this detection."""

    plain_english_text: str
    """Non-empty plain-English description ≤ 500 characters."""

    evidence: dict
    """Structured evidence from the ThreatEvent."""

    confidence_score: int
    """Integer in [0, 100]."""

    severity: str
    """One of: Low | Medium | High | Critical."""

    recommendation: str
    """Actionable remediation advice for the administrator."""


# ---------------------------------------------------------------------------
# BaseRule interface
# ---------------------------------------------------------------------------

class BaseRule(ABC):
    """
    Abstract base class for all NetGuard detection rules.

    Subclasses implement one detection rule each.  The Detection_Engine calls
    these methods on every packet in sequence:

        rule.process_packet(packet)  # update internal counters
        event = rule.evaluate()      # check thresholds; return ThreatEvent or None

    Subclasses MUST NOT raise exceptions to the caller — all errors are caught
    by the Detection_Engine (Requirement 9.5, 9.7).
    """

    #: Detection rule identifier — override in subclass
    rule_name: str = ""

    #: Human-readable attack category — override in subclass
    attack_type: str = ""

    #: Whether this rule is currently enabled (class-level default)
    enabled: bool = True

    def __init__(self) -> None:
        """
        Initialise base instance attributes from class-level declarations.

        Copies ``rule_name``, ``attack_type``, and ``enabled`` from the class
        onto the instance so that each rule object has independent state.

        Subclasses that override ``__init__`` should call ``super().__init__()``
        or set these attributes themselves (Requirement 9.4).
        """
        # Promote class-level defaults to instance attributes so that per-instance
        # mutation (e.g. disabling a single rule object) does not affect the class.
        self.rule_name: str = self.__class__.rule_name
        self.attack_type: str = self.__class__.attack_type
        self.enabled: bool = True

    @abstractmethod
    def initialize(self) -> None:
        """
        One-time initialisation called before the first packet is processed.

        Load rule configuration, reset counters, set up data structures.
        """

    @abstractmethod
    def process_packet(self, packet: Packet) -> None:
        """
        Update internal counters / state for the given packet.

        Must be fast (< few ms).  Must not raise.

        Args:
            packet: Normalised packet from PacketDecoder.
        """

    @abstractmethod
    def evaluate(self) -> Optional[ThreatEvent]:
        """
        Evaluate current counters against the detection threshold.

        Called after every process_packet().  Returns a ThreatEvent if the
        threshold is exceeded, or None if no detection yet.

        Must not raise.

        Returns:
            ThreatEvent if an attack is confirmed, otherwise None.
        """

    @abstractmethod
    def generate_event(self) -> ThreatEvent:
        """
        Build a ThreatEvent from the current accumulated evidence.

        Called internally by evaluate() when a threshold is exceeded.

        Returns:
            A fully populated ThreatEvent.
        """

    @abstractmethod
    def explain(self, event: ThreatEvent) -> Explanation:
        """
        Generate a human-readable Explanation for the given ThreatEvent.

        Args:
            event: The ThreatEvent to explain.

        Returns:
            A fully populated Explanation object.
        """

    @abstractmethod
    def cleanup(self) -> None:
        """
        Release resources and reset state.

        Called when the rule is disabled or the application shuts down.
        """
